### ISSUE TITLE
define RNAseq results as outputs in immuno.wdl

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/analysis-wdls#32]

**Comment by malachig** [comment]
Working on this and think I have most of it working.  Still outstanding are:
- the strandedness test results.  We could probably store these in the QC results dir for rna
- the fusion inspector results.  there are many files here.  simplest solution would be to zip up the whole results dir and store that as a final input in immuno.wdl

**Comment by malachig** [comment]
This is done and working now.
