### ISSUE TITLE
Gracefully handle partial optitype HLA typing

### ISSUE THREAD

**Issue by malachig** [griffithlab/analysis-wdls#50]
This issue was discovered using a downsampled input data set.

If Optitype is unable to type an HLA gene, it reports a blank entry for that column.  

This causes a failure in the extract HLA allele step of the immuno.wdl workflow.  This step expects all six HLA allele entries to be present. But if there isn't enough data to call one or more, optitype still completes successfully and reports what it can.  This seems reasonable and we should handle this case and proceed with whatever HLA alleles we get.

We believe the problematic line is this awk here:
https://github.com/griffithlab/analysis-wdls/blob/513d16782c93acbdda23949e03c17035128613ca/definitions/tools/extract_hla_alleles.wdl#L17

**Comment by Layth17** [comment]
Currently, if there is a black entry, the positional arguments will shift
for example:
if input is:
`        A1      A2      B1      B2      C1      C2      Reads   Objective
0       A*03:01 A*03:01         B*07:02 C*07:02 C*17:01 22224.0 21823.967999999917`

output will be:

`HLA-A*03:01
HLA-A*03:01
HLA-B*07:02
HLA-C*07:02
HLA-C*17:01
HLA-22224.0`

How do you want `B1` to be reported instead? ... options:

a)
`HLA-A*03:01
HLA-A*03:01
HLA-B*07:02
HLA-C*07:02
HLA-C*17:01`

b)
`HLA-A*03:01
HLA-A*03:01
HLA-B*<leave blank?>
HLA-B*07:02
HLA-C*07:02
HLA-C*17:01`

or something else?

**Comment by chrisamiller** [comment]
I imagine the right answer is to change that awk to something that doesn't rely on positional arguments at all - an inline perl snippet or little python script or something.  Assuming you want fields 2 through N, an offhand (untested) example might be something like: 

`cat file | perl -nae 'for(my $i=1;$i<@F;$i++){print "HLA-$F[$i]\n"} >outfile`

**Comment by Layth17** [comment]
By changing the -FS to \t I was able to detect the empty field. I just don't know the best way to handle it in the output without the pipeline failing.

**Comment by Layth17** [comment]
`awk '{FS="\t";getline;for(n=2;n<8;n++){if(n==2){printf "HLA-"$n}else{printf "\nHLA-"$n}}}'`

```HLA-A*03:01
HLA-A*03:01
HLA-
HLA-B*07:02
HLA-C*07:02
HLA-C*17:01
```

**Comment by malachig** [comment]
I think if we don't have a valid HLA allele, we want to just exclude the entry all together.  And not include something like `HLA-`
